name: CI/CD Pipeline

on:
  push:
    branches:
      - main
#Runner
jobs:
  composer_Development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ github.ref_name }}-composer
          restore-keys: |
            ${{ github.ref_name }}-composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Upload vendor directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vendor
          path: vendor/

  npm_Development:
    runs-on: ubuntu-latest
    needs: composer_Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.ref_name }}-npm
          restore-keys: |
            ${{ github.ref_name }}-npm

      - name: Install npm dependencies
        run: npm install

      - name: Run development build
        run: npm run dev

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            public/css/
            public/js/
            public/mix-manifest.json

