name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch :

jobs:
  composer_development:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install Composer dependencies
      run: composer install  --no-progress --no-suggest --prefer-dist --optimize-autoloader 
      
  NPM_install:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
        - name: Install npm dependencies
          run: npm install
        - name: Build assets
          run: npm run build
        
  zipping_and_Upload_ZIP_S3:

    runs-on: ubuntu-latest
    needs: [composer_development, NPM_install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get environment variables from Parameter Store
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      - name: Sync files to S3
        run: |
            zip -r ${{ github.run_id }}.zip . #-x '*.git*' -x 'node_modules/*' -x 'vendor/*' -x '.github/*' -x 'tests/*' -x 'storage/*' -x '.idea/*'
            aws s3 cp ${{ github.run_id }}.zip s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.run_id }}.zip
        env:
          CODEDEPLOY_APPLICATION_NAME: ${{ secrets.CODEDEPLOY_APPLICATION_NAME }}
          CODEDEPLOY_GROUP_NAME: ${{ secrets.CODEDEPLOY_GROUP_NAME }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
